id: P1BC109B2
initial_creation_type: ocr
source_metadata:
  volumes:
    9e063ccebf3b4e318000b25012f70143:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཕྱག་ན་རྡོ་རྗེའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1379
      volume_number: 37
